runtime: python3123

entrypoint: gunicorn -p :8080 app:app

env: standard

instance_class: F1  # Default instance class, adjust if needed

automatic_scaling:
  min_instances: 1
  max_instances: 3

handlers:
- url: /.*
  script: auto
